# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          rustem.co
paginate:       5
baseurl:        "/"
url:            "http://rustem.co"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Mukharamov Rustem
  url:          http://rustem.co
  email:        mukharamov.r.m@gmail.com

# Custom vars
version:        1.0.1
github:
  repo:         https://github.com/lifeIsGame/blog

# Gems
plugins:
  - jekyll-paginate
